owner: sanderDijkxhoorn
repo: uptime
sites: 
  - name: Zyki
    url: https://zyki.net/
  - name: Zyki school
    url: https://school.zyki.net/

assignees: 
  - sanderDijkxhoorn
status-website: # Status website (optional)
  cname: uptime.zyki.net # Custom domain CNAME
  name: Uptime # Status website title
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "Welcome :)"
  introMessage: Bla bla bla text here
  navbar:
    - title: Uptime
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
