owner: sanderDijkxhoorn
repo: uptime
sites: 
  - name: zyki.net
    url: https://zyki.net/
  - name: school.zyki.net
    url: https://school.zyki.net/
  - name: status.zyki.net
    url: https://status.zyki.net/
  - name: zyki.nl
    url: http://zyki.nl/

assignees: 
  - sanderDijkxhoorn
status-website: # Status website (optional)
  cname: uptime.zyki.net # Custom domain CNAME
  name: Uptime # Status website title
  logoUrl: https://raw.githubusercontent.com/sanderDijkxhoorn/uptime/master/assets/bell.svg
  theme: dark
  #introTitle: "Welcome :)"
  #introMessage: Bla bla bla text here...
  navbar:
    - title: Uptime
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
